<?php
/**
 * @package urlive_widget
 * @version 1.0.0
 */
/*
Plugin Name: Urlive Call Widget
Plugin URI: http://wordpress.org/plugins/urlive-widget/
Description: This is plugin is to add the urlive chat widget to your wordpress site
Author: Tunde Kadiri
Version: 1.0.0
Author URI: https://url.live/Tunde
*/


function urll_load_plugin_scripts(){
	//loading js
	wp_register_script('jquery-core', plugins_url('/wp-includes/js/jquery/jquery.js'));
	
	wp_add_inline_script('jquery-core', 'function restartCode() {
        window.open("https://url.live/App?displayPage=APPS", "_blank");
        jQuery("#widget-form2").css("display", "block");
        jQuery("#restart").css("display", "none");
		};');

	wp_add_inline_script('jquery-core', 'function enterCode() {
        window.open("https://url.live/App?displayPage=APPS", "_blank");
        jQuery("#widget-form1").css("display", "block");
		 };');

         wp_enqueue_script('jquery-core');
	//loading css
	wp_register_style('bootstrap-style', '//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css');
	wp_enqueue_style('bootstrap-style');

	wp_register_style('urll_style', plugins_url('URLL_widget/urll_style.css'));
	wp_enqueue_style('urll_style');

 
}

//**********************************************
//. ************ SETTINGS SECTION **************
//**********************************************



//. The setting fields will know which settings your options page will handle.
/*. The function 'urlive_plugin_admin' will be called when wordpress calls the admin_menu function which is built into the wordpress site */

//add_action('admin_enqueue_scripts', 'urll_load_plugin_scripts'); 
add_action('admin_init', 'urlive_admin_init');

function urlive_admin_init(){
    // The first argument is a group, which needs to be the same as what you used in the settings_fields function call. The second argument is the name of the options. 
    register_setting('urlive_plugin_options', 'urlive_plugin_options');

    //If we were doing more than one, we’d have to call this over and over for each separate setting. The final arguement is a function name that will validate your options.
    register_setting('urlive_plugin_paste_code', 'urlive_plugin_paste_code');
  
    /*
    The first argument is simply a unique id for the section.
    The second argument is the title or name of the section (to be output on the page).
    The third is a function callback to display the guts of the section itself.
    The fourth is a page name. This needs to match the text we gave to the do_settings_sections function call.
    */
    add_settings_section('urlive_plugin_main', '', '', 'plugin');  
    add_settings_section('urlive_plugin_code', '', '', 'plugin');  
    add_settings_section('urlive_plugin_register', '', '', 'plugin');  
    add_settings_section('urlive_code_widget', '', '', 'pluginPaste');

    /*
     * The first arguement is the id of the field
     * The Second Arguement is the title of the field
     * The third arguement is the callback function 
     * The fourth arguement is th epage that it will be displayed on
     * The fifth arguement is the section of the page that the field should be added to 
     */
    //add_settings_field('urlive_input_login', '', 'urlive_plugin_section1', 'plugin', 'urlive_plugin_main');
    add_settings_field('urlive_input_code', 'Enter Widget Code', 'urlive_code_input', 'plugin', 'urlive_plugin_code');
    //add_settings_field('urlive_input_register', '', 'urlive_plugin_section3', 'plugin', 'urlive_plugin_register');
    //add_settings_field('urlive_widget_code', 'Widget Code', 'urlive_code_input', 'pluginPaste', 'urlive_code_widget');

}

// Launches the urlive_plugin_menu when wordpress runs its built in function 'admin_menu'
add_action('admin_menu', 'urlive_plugin_admin');

function urlive_plugin_admin() {
	urll_load_plugin_scripts();
    // This function will create the different pages that will be in the settings for the Urlive plugin
    // add options page will create a link in the settings tab for the admin clicking on this link will launch the main settings page
    add_options_page('Get Started', 'Urlive', 'manage_options', 'plugin', 'urlive_plugin_options_page');


    //This page will be the success activated page
    /*
    a. It adds a link under the settings menu called �Urlive�.
    b. When you click it, you go to a page with a title of �Get Started�.
    c. You must have the �manage_options� capability to get there though (admins only).
    d. The link this will be will in fact be /wp-admin/options-general.php?page=plugin (so �plugin� needs to be something only you will use).
    e. And the content of the page itself will be generated by the �urlive_plugin_options_page� function.
    */
    //add_menu_page('Account linked', 'Urlive linked', 'manage_options', 'pluginLinked', 'urlive_plugin_options_linked');
    // This is to add another menu page (SUCCESSFULLY LINKED) to the Urlive plugin set up
    //add_menu_page('Paste Widget Code', 'Paste Code', 'manage_options', 'pluginPaste', 'urlive_plugin_options_paste');
    // This is the login in page
    //add_menu_page('Link Account', 'Link to urLive', 'manage_options', 'pluginLogin', 'urlive_plugin_options_login');
}

?>

<?php function urlive_plugin_options_page() {
    // display the admin options page
    $user = urlive_finduser(get_option('urlive_plugin_paste_code')['widget_code']);
    if(isset(get_option('urlive_plugin_paste_code')['widget_code']) && !empty(get_option('urlive_plugin_paste_code')['widget_code'])) 
    {
        urlive_user();
    }
    else 
    {   
        urlive_new_user();
    }
    
}

function urlive_user(){
    ?>
   <!--  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel = "stylesheet" href="../wp-content/plugins/URLL_widget/urll_style.css"> -->

    <div class = "urll_body">
    <div id = "Page2">
        <h2 style = "text-align: center;">Success! Your Widget is now Linked to url.live/<?php echo urlive_finduser(get_option('urlive_plugin_paste_code')['widget_code']); ?></h2>
        <p style = "text-align: center;">Chat with visitors to your website, capture them as leads, and convert them to customers.</p>
        <p style = "text-align: center;"><b>We hope you have a great time connecting with family & friends.</b></p> 

        <button id = "restart" onclick = "restartCode()">Restart Setup</button>
        <!-- <a href = 'options-general.php?page=pluginPaste'>Second page</a> -->
        <form style = 'display: none' id = "widget-form2" action="options.php" method="post">
        <!-- This outputs the hidden bits that we need to make our options page both do what we want and to make it secure with a nonce. The string �plugin-options� can be anything, as long as it�s unique. -->
        <?php settings_fields('urlive_plugin_paste_code'); ?>

        <!-- This is going to output all of our input fields. Text input boxes, radio fields, anything we like -->
        <?php
            do_settings_sections('plugin'); 
        ?>
 
        <input class = 'url_input' name="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" />
        </form>

   <!-- <script> 
		$("#restart").click(function() {
        window.open("https://url.live/App?displayPage=APPS", "_blank");
        $("#widget-form2").css("display", "block");
        $("#restart").css("display", "none");
		});
    </script> -->
    </div>
    </div>
<?php
}

function urlive_new_user() {
    ?>
   <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel = "stylesheet" href="../wp-content/plugins/URLL_widget/urll_style.css"> -->

    <div class = "urll_body">
    <div id = "Page1">
    <h2 style = "text-align: center;">Get Started with urLive</h2>
    <p style = "text-align: center;">Chat with visitors to your website, capture them as leads, and convert them to customers.</p>
    <p style = "text-align: center;"><b>Install urLive on your Wordpress site in just a few clicks</b></p> 
    <!-- <a href = 'options-general.php?page=pluginPaste'>Second page</a> -->
    <button id = "enter-code" onclick = "enterCode()">Input Widget Code</button>
    <p id = "urlive_input_register" href = "">Not a Member yet? <a href = "https://url.live" target = "blank">Create an Account</a></p>

    <form style = "display: none;" id = "widget-form1" action="options.php" method="post">
        <?php settings_fields('urlive_plugin_paste_code'); ?>
        <?php
            do_settings_sections('plugin'); 
        ?>
        <input class = 'url_input' name="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" />
        </form>
    </div>
    <div>

 <!--    <script> 
    $('#enter-code').click(function() {
        window.open("https://url.live/App?displayPage=APPS", '_blank');
        $('#widget-form1').css('display', 'block');
    });
    </script> -->
    <?php
}

function urlive_plugin_options_linked() {
    ?>
        <div>
            <h2>Success! Your urLive is now Connected</h2>
            <p>Chat with visitors to your website, capture them as leads, and convert them to customers.</p>
            <p><b>We hope you have a great time connecting with family & friends.</b></p>
            <form action="options.php" method="post">
            <?php settings_fields('urlive_plugin_paste_code'); ?>
            <?php do_settings_sections('pluginPaste'); 
    ?>
     
    <!-- <input name="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" /> -->
            </form>
        </div>
     
    <?php
    }

function urlive_plugin_options_paste() {
    // display the admin options page
?>
    <div>
        <h2>Urlive plugin Paste</h2>
        The second settings page
        <form action="options.php" method="post">
        <?php settings_fields('urlive_plugin_paste_code'); ?>
        <?php do_settings_sections('pluginPaste'); ?>
 
        <input name="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" />
        </form>
</div>
 
<!-- 
    ***********************************************
    ******************* END PAGES *****************
    ***********************************************
-->

<?php 
}

function urlive_plugin_section3(){
    echo '<p id = "urlive_input_register" href = "">Not a Member yet? <a href = "https://url.live" target = "blank">Create an Account</a></p>';
}

function urlive_code_input() {
     $options = get_option('urlive_plugin_paste_code');
     echo "
     <TextArea class='textarea-widget' id='urlive_input_text' name='urlive_plugin_paste_code[widget_code]' type='text'>{$options['widget_code']}</TextArea>
     ";
}    

add_action('wp_footer', 'urlive_display_chat_widget');

function urlive_display_chat_widget() {
    $widget_code = get_option('urlive_plugin_paste_code')['widget_code'];
   echo $widget_code;

}
?>

<?php 

function urlive_finduser($string){
    $start_idx = strpos($string, "er=");
    $end_idx = strpos($string, "&Requested");

    $start_idx = $start_idx + 3;
    $end_idx = $end_idx;
    $length = abs($start_idx - $end_idx);
    $username = substr($string, $start_idx, $length);
    return $username;
}
?>
